### ISSUE TITLE
Communication Fault: 0

### ISSUE THREAD

**Issue by yNosGR** [Booozie-Z/Fanuc_GESRTP_Driver#2]
Please forgive my noobness, this is my first python project in a while. I am trying to switch over to your driver from the "ge-ethernet-srtp" to your driver in order to get some floats off a fanuc 30-70 plc with a CMM321 ethernet interface - I am running into a "Communication Fault:0" error that I'm not sure how to work through.  We are running python version 3.9.2
```
import robot_comm

sock = robot_comm.open_socket("plc.site1", 18245) 
print("R1   :", robot_comm.decode_register(robot_comm.read_mem(112, "R", sock)))
sock.close()

```
returns
```Traceback (most recent call last):
  File "/home/br/src/Fanuc_GESRTP_Driver/./craig.py", line 3, in <module>
    sock = robot_comm.open_socket("plc.site1", 18245) 
  File "/home/br/src/Fanuc_GESRTP_Driver/robot_comm.py", line 27, in open_socket
    raise Exception("Communication Fault: ", init_comm)
Exception: ('Communication Fault: ', 0)
```
I've added some rudimentary logging, I hope it helps..
```
read_mem_message:b'\x02' b'\x00' b'\x06' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x01' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x01' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x06' b'\xc0' b'\x00' b'\x00' b'\x00' b'\x00' b'\x10' b'\x0e' b'\x00' b'\x00' b'\x01' b'\x01' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00' b'\x00'
Communication fault:0
```
EDIT 1: A little more poking around in ipython:
```
In [18]: s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

In [19]: s.connect((robot_ip, snpx_port))

In [20]: s.send(srtp_message.INIT_MSG)
Out[20]: 56

In [21]: init_resp = s.recv(1024)

In [22]: print(init_resp[0])
1

In [23]: init_comm = read_mem(0, "R", s)

In [24]: print(init_comm)
0
In [25]: s.close()
```

**Comment by yNosGR** [comment]
It ended up being a problem in init_comm
 [Proposed fix](https://github.com/Booozie-Z/Fanuc_GESRTP_Driver/pull/3)
